version: "3.0"

services:

  marketplace:
    image: 045498435234.dkr.ecr.us-west-2.amazonaws.com/zervmarketplace:ci_latest
    env_file:
    - envfile.env
    environment:
    - MONGO_URL=mongodb+srv://suku:mqMGttyFShizYkOnbFLXjo@sukusharedmongodb-miu9y.mongodb.net/test?retryWrites=true/marketplace
    
  authentication:
    image: 045498435234.dkr.ecr.us-west-2.amazonaws.com/zervauthentication:ci_latest
    env_file:
    - envfile.env
    environment:
    - MONGO_URL=mongodb+srv://suku:mqMGttyFShizYkOnbFLXjo@sukusharedmongodb-miu9y.mongodb.net/test?retryWrites=true/DATA

  mailer:
    image: 045498435234.dkr.ecr.us-west-2.amazonaws.com/zervmailer:ci_latest
    env_file:
    - envfile.env
    environment:
    - MONGO_URL=mongodb+srv://suku:mqMGttyFShizYkOnbFLXjo@sukusharedmongodb-miu9y.mongodb.net/test?retryWrites=true/crgeneric

  review:
    image: 045498435234.dkr.ecr.us-west-2.amazonaws.com/zervreview:ci_latest
    env_file:
    - envfile.env
    environment:
    - MONGO_URL=mongodb+srv://suku:mqMGttyFShizYkOnbFLXjo@sukusharedmongodb-miu9y.mongodb.net/test?retryWrites=true/review

  trackandtrace:
    image: 045498435234.dkr.ecr.us-west-2.amazonaws.com/zervtrackandtrace:ci_latest
    env_file:
    - envfile.env
    environment:
    - MONGO_URL=mongodb+srv://suku:mqMGttyFShizYkOnbFLXjo@sukusharedmongodb-miu9y.mongodb.net/test?retryWrites=true/trackData

  notification:
    image: 045498435234.dkr.ecr.us-west-2.amazonaws.com/zervnotification:ci_latest
    env_file:
    - envfile.env
    environment:
    - MONGO_URL=mongodb+srv://suku:mqMGttyFShizYkOnbFLXjo@sukusharedmongodb-miu9y.mongodb.net/test?retryWrites=true/notificationDb

  matchmaking:
    image: 045498435234.dkr.ecr.us-west-2.amazonaws.com/zervmatchmaking:ci_latest
    env_file:
    - envfile.env
    environment:
    - MONGO_URL=mongodb+srv://suku:mqMGttyFShizYkOnbFLXjo@sukusharedmongodb-miu9y.mongodb.net/test?retryWrites=true/matchData

  chatservices:
    image: 045498435234.dkr.ecr.us-west-2.amazonaws.com/zervchatservices:ci_latest
    env_file:
    - envfile.env
    environment:
    - MONGO_URL=mongodb+srv://suku:mqMGttyFShizYkOnbFLXjo@sukusharedmongodb-miu9y.mongodb.net/test?retryWrites=true/chatData

  ui:
    image: 045498435234.dkr.ecr.us-west-2.amazonaws.com/zervplatformv5api:ci_latest
    depends_on: 
    - marketplace
    - authentication
    - mailer
    - review
    - trackandtrace
    - notification
    - matchmaking
    - chatservices

  proxy:
    build: proxy
    ports:
    - "80:80" 
    depends_on: 
    - ui


volumes:
     mongo_data:
